var AssDocGeneral = function(content){
    this.content = content;
    this.GetDG= function (){
            var layout = //"<div class='form-group row'><label class='col-sm-5 col-form-label'><u><b>Mental Status Examination </b></u></label></div>"
            "<div class='form-group row'><label class='col-sm-2 col-form-label'><b>1. Psychomotor </b></label><div class='col-sm-2'><input class='ace' type='radio' name='psych_chk' value='N'checked required><span class='lbl'> Normal</span></label></div><div class='col-sm-2'><input class='ace' type='radio' name='psych_chk' value='Y' required><span class='lbl'> Abnormal</span></div>"
                +"<div class='col-sm-6'><input type='text' name='psych' id='psych' class='form-control' placeholder=''></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b>2. Speech </b></label><div class='col-sm-2'><input class='ace' type='radio' name='speech_chk' value='N'checked required><span class='lbl'> Normal</span></label></div><div class='col-sm-2'><input class='ace' type='radio' name='speech_chk' value='Y' required><span class='lbl'> Abnormal</span></div>"
                +"<div class='col-sm-6'><input type='text' name='speech' id='speech' class='form-control' placeholder=''></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b>3. Mood & Affect </b></label><div class='col-sm-2'><input class='ace' type='radio' name='MA_chk' value='N'checked required><span class='lbl'> Normal</span></label></div><div class='col-sm-2'><input class='ace' type='radio' name='MA_chk' value='Y' required><span class='lbl'> Abnormal</span></div></div>"
            +"<div class='form-group row' id='MA_group'><div class='col-sm-2'></div><div class='col-sm-3'><input class='ace' type='checkbox' name='MA_1' value='1'><span class='lbl'> Depress/Elevate/Irritable/Labile</span></label></div><div class='col-sm-3'><input class='ace' type='checkbox' name='MA_2' value='2'><span class='lbl'> Anxiety/Agitation/Guilt/shame</span></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-5 col-form-label'><b>4. Thought </b></label></div>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b> - From of thought </b></label><div class='col-sm-2'><input class='ace' type='radio' name='FT_chk' value='N'checked required><span class='lbl'> Normal</span></label></div><div class='col-sm-2'><input class='ace' type='radio' name='FT_chk' value='Y' required><span class='lbl'> Abnormal</span></div></div>"
                +"<div class='form-group row' id='FT_group'><div class='col-lg-2'>&nbsp;</div><label class='col-sm-5 col-form-label'>Incoherent/Irrelevant/Loosening of Association/Flight of Idea </label><div class='col-sm-5'><input type='text' name='FT' id='FT' class='form-control' placeholder=''></div></div>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b> - Content of thought </b></label><div class='col-sm-2'><input class='ace' type='radio' name='CT_chk' value='N'checked required><span class='lbl'> Normal</span></label></div><div class='col-sm-2'><input class='ace' type='radio' name='CT_chk' value='Y' required><span class='lbl'> Abnormal</span></div></div>"
            +"<div class='form-group row' id='CT_group'><div class='col-sm-2'></div><div class='col-sm-1'><input class='ace' type='checkbox' name='CT_1' value='1'><span class='lbl'> Phobia</span></label></div><div class='col-sm-2'><input class='ace' type='checkbox' name='CT_2' value='2'><span class='lbl'> Preoccupation</span></div><div class='col-sm-2'><label><input class='ace' type='checkbox' name='CT_3' value='3'><span class='lbl'> Obsessional</span></label></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b>5. Perception </b></label><div class='col-sm-2'><input class='ace' type='radio' name='perception_chk' value='N'checked required><span class='lbl'> Normal</span></div><div class='col-sm-2'><input class='ace' type='radio' name='perception_chk' value='Y' required><span class='lbl'> Abnormal</span></div></div>"
            +"<div class='form-group row' id='perception_group'><div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-2'><input class='ace' type='checkbox' name='percep_1' value='1'><span class='lbl'> Hallucination</span></div><div class='col-sm-8'><input type='text' name='Halluc' id='Halluc' class='form-control form-control-sm' placeholder=''></div></div><br>"
                                                                +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-2'><input class='ace' type='checkbox' name='percep_2' value='2'><span class='lbl'> Illusion</span></div><div class='col-sm-8'><input type='text' name='Illusion' id='Illusion' class='form-control form-control-sm' placeholder=''></div></div><br>"
                                                                +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-3'><input class='ace' type='checkbox' name='percep_3' value='3'><span class='lbl'> Depersonalization</span></div></div><br>"
                                                                +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-3'><input class='ace' type='checkbox' name='percep_4' value='4'><span class='lbl'> Derealization</span></div></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-2 col-form-label'><b>6. Insight & Judgment </b></label><div class='col-sm-1'><input class='ace' type='radio' name='IJ_chk' value='1'><span class='lbl'> Poor</span></div><div class='col-sm-1'><input class='ace' type='radio' name='IJ_chk' value='2'><span class='lbl'> Fair</span></div>"
            +"<div class='col-sm-1'><label><input class='ace' type='radio' name='IJ_chk' value='3'><span class='lbl'> Good</span></label></div><div class='col-sm-7'><input class='form-control form-control-sm' type='text' id='good' name='good' placeholder='' /></div></div>"
            //+"<hr>"
            +"<div class='form-group row'><label class='col-sm-5 col-form-label'><b>7. Sensorium & Cognition </b></label></div>"
            +"<div class='form-group row' id='SC_group'><div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-2'><input class='ace' type='checkbox' name='SC_1' value='1'><span class='lbl'> Orientaion</span></div><div class='col-sm-8'><input type='text' name='Orientaion' id='Orientaion' class='form-control form-control-sm' placeholder=''></div></div><br>"
                                                        +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-2'><input class='ace' type='checkbox' name='SC_2' value='2'><span class='lbl'> Gemeral Knowiedge</span></div><div class='col-sm-8'><input type='text' name='Gemeral' id='Gemeral' class='form-control form-control-sm' placeholder=''></div></div><br>"
                                                        +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-2'><input class='ace' type='checkbox' name='SC_3' value='3'><span class='lbl'> Abstract Thinking</span></div><div class='col-sm-8'><input type='text' name='Abstract' id='Abstract' class='form-control form-control-sm' placeholder=''></div></div><br>"
                                                        +"<div class='col-lg-12 row'><div class='col-lg-2'>&nbsp;</div><div class='col-lg-3'><input class='ace' type='checkbox' name='SC_4' value='4'><span class='lbl'> Attention & Concentration</span></div><div class='col-sm-7'><input type='text' name='Attention' id='Attention' class='form-control form-control-sm' placeholder=''></div></div></div>"
                                                        //+"<hr>";
        $(this.content).empty().append(layout);
    }
}
